### ISSUE TITLE
Failing across multiple repos on v12.1835.0

### ISSUE THREAD

**Issue by exosyphon-rxrevu** [bridgecrewio/checkov-action#111]
We are seeing multiple repos fail when running checkov-action. See stack trace below.

```
running checkov on directory: modules/
checkov -d modules/    --quiet   --output github_failed_only --soft-fail  --download-external-modules true    --framework terraform --create-baseline  
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 330, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 79, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 113, in run
    local_graph, self.definitions = self.graph_manager.build_graph_from_source_directory(
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_manager.py", line 45, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/local_graph.py", line 61, in build_graph
    renderer.render_variables_from_local_graph()
  File "/usr/local/lib/python3.8/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 32, in render_variables_from_local_graph
    self._render_variables_from_vertices()
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line [28](https://github.com/rxrevu/infrastructure/actions/runs/3423920899/jobs/5703043661#step:5:29)7, in _render_variables_from_vertices
    self._render_dynamic_blocks()
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line [29](https://github.com/rxrevu/infrastructure/actions/runs/3423920899/jobs/5703043661#step:5:30)8, in _render_dynamic_blocks
    rendered_blocks = self._process_dynamic_blocks(dynamic_blocks)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line [34](https://github.com/rxrevu/infrastructure/actions/runs/3423920899/jobs/5703043661#step:5:35)2, in _process_dynamic_blocks
    block_conf[dynamic_argument] = dynamic_value[dynamic_value_in_map]
KeyError: 'bucket_name'
```

**Comment by ChanochShayner** [comment]
Hey, @exosyphon-rxrevu thanks, 
we're investigating it and working on a fix.
This issue comes from the progress we doing now on rendering dynamic blocks, so if you can share with us the problematic templates, then it would be easier to fix the issue, Thanks.

**Comment by gruebel** [comment]
a new version (`v12.1836.0`) with a fix was released, but hard to tell, if it is the only problem without having the original templates.

**Comment by exosyphon-rxrevu** [comment]
Here is the workflow yaml we are using. Looks like it is still failing today.

```
name: CHECKOV

on: pull_request

jobs:
  checkov-job:
    runs-on: ubuntu-latest
    name: checkov-action
    steps:
      - name: "📥 Check-out"
        uses: actions/checkout@v2
        with:
          ref: ${{github.base_ref}}

      # docs: https://github.com/bridgecrewio/checkov-action
      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: modules/
          quiet: true
          soft_fail: true
          framework: terraform --create-baseline
          output_format: github_failed_only
          download_external_modules: true

      - name: capture-baseline
        run: |
          cp modules/.checkov.baseline /tmp

      - name: "📥 Check-out"
        uses: actions/checkout@v2

      - name: return-baseline
        run: |
          cp /tmp/.checkov.baseline ./new_baseline

      - name: Run Checkov action
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          quiet: true # optional: display only failed checks
          soft_fail: true # optional: do not return an error code if there are failed checks
          framework: terraform # optional: run only on a specific infrastructure {cloudformation,terraform,kubernetes,all}
          output_format: github_failed_only # optional: the output format, one of: cli, json, junitxml, github_failed_only
          baseline: new_baseline # Only report results not already in the baseline, ideally ignoring root module errors
          download_external_modules: true
```

**Comment by exosyphon-rxrevu** [comment]
Here is the error we are getting today. Appreciate ya'll working on this.

```
running checkov on directory: modules/
checkov -d modules/    --quiet   --output github_failed_only --soft-fail  --download-external-modules true    --framework terraform --create-baseline  
Traceback (most recent call last):
  File "/usr/local/bin/checkov", line 9, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.8/site-packages/checkov/main.py", line 330, in run
    scan_reports = runner_registry.run(root_folder=root_folder, external_checks_dir=external_checks_dir,
  File "/usr/local/lib/python3.8/site-packages/checkov/common/runners/runner_registry.py", line 79, in run
    self.runners[0].run(root_folder, external_checks_dir=external_checks_dir, files=files,
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/runner.py", line 113, in run
    local_graph, self.definitions = self.graph_manager.build_graph_from_source_directory(
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_manager.py", line 45, in build_graph_from_source_directory
    local_graph.build_graph(render_variables=render_variables)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/local_graph.py", line 61, in build_graph
    renderer.render_variables_from_local_graph()
  File "/usr/local/lib/python3.8/site-packages/checkov/common/graph/graph_builder/variable_rendering/renderer.py", line 32, in render_variables_from_local_graph
    self._render_variables_from_vertices()
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line [28](https://github.com/rxrevu/infrastructure/actions/runs/3424143611/jobs/5715892427#step:4:29)8, in _render_variables_from_vertices
    self._render_dynamic_blocks()
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line [29](https://github.com/rxrevu/infrastructure/actions/runs/3424143611/jobs/5715892427#step:4:30)9, in _render_dynamic_blocks
    rendered_blocks = self._process_dynamic_blocks(dynamic_blocks)
  File "/usr/local/lib/python3.8/site-packages/checkov/terraform/graph_builder/variable_rendering/renderer.py", line [36](https://github.com/rxrevu/infrastructure/actions/runs/3424143611/jobs/5715892427#step:4:37)0, in _process_dynamic_blocks
    next_key = next(iter(block_content[DYNAMIC_STRING].keys()))
AttributeError: 'list' object has no attribute 'keys'
```

**Comment by ChanochShayner** [comment]
@exosyphon-rxrevu Thanks for the update,
 It seems that the resource that is failing is a nested dynamic module, it will help us a lot if you can share with us the problematic TF nested module (or an example of it), then it would be easier to fix the issue, Thanks.

**Comment by exosyphon-rxrevu** [comment]
Heres the layout that we are using:

/modules/alb/main.tf

Everything is under the modules folder but there are many more folders similar to the alb one and all of them currently fail.

**Comment by ChanochShayner** [comment]
@exosyphon-rxrevu Thanks, but if you can share with us the `specific resource` that cause the action to fail it helps us support those kinds of nested dynamic block resources.
Example of nested resource that we are currently supporting - [Here](https://github.com/bridgecrewio/checkov/blob/master/tests/terraform/graph/variable_rendering/test_resources/dynamic_blocks_with_nested/main.tf)

**Comment by dennisbrouwer91** [comment]
We are facing the same issue on our CheckOV runs, it works on 2.2.35, but after that it stopped. We reference a TF Module that is privately stored in Terraform Cloud. Maybe that helps with debugging?

**Comment by ChanochShayner** [comment]
Hey, @dennisbrouwer91 thanks for the update,
 - I've opened a PR to fix the specific `AttributeError` that cause your action to fail, and also warp all the new flow with try-except to avoid crashing on this.
 - Yes, if you can share the TF resource and the module (or an example of it) it will help us a lot.

**Comment by dennisbrouwer91** [comment]
Hey @ChanochShayner , do you have a link to the PR so i can check?
This is how we reference the module : 
`module "tags" {
  source      = "app.terraform.io/<orgname>/tags/aws"
  version     = "~> 0.1.0"
}`

**Comment by ChanochShayner** [comment]
Sure, here is the [PR](https://github.com/bridgecrewio/checkov/pull/3837),
Regarding the TF Module/resource - I am trying to understand the big picture, you can see in the attached PR a full case of a resource with dynamic blocks (with the variables.tf locals.tf module.tf files), so if you can share more about the specific resource it will help us.

**Comment by gruebel** [comment]
feel free to reach out, if you still have problems.
